<?php

namespace Database\Seeders;

use App\Models\Prospecto;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProspectoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $vendedor = User::first();

        $prospectos = [
            // Prospectos Residenciales
            [
                'nombre' => 'Carlos',
                'apellidos' => 'Mendoza Ríos',
                'tipo_persona' => 'natural',
                'dni' => '45678912',
                'email' => 'carlos.mendoza@gmail.com',
                'telefono' => '014567890',
                'celular' => '987654321',
                'direccion' => 'Av. La Molina 1234, La Molina',
                'origen' => 'web',
                'origen_detalle' => 'Formulario de cotización web',
                'segmento' => 'residencial',
                'scoring' => 'A',
                'scoring_puntos' => 85,
                'estado' => 'calificado',
                'consumo_mensual_kwh' => 450,
                'factura_mensual_soles' => 350,
                'tipo_inmueble' => 'casa',
                'area_disponible_m2' => 80,
                'tiene_medidor_bidireccional' => false,
                'empresa_electrica' => 'Luz del Sur',
                'presupuesto_estimado' => 25000,
                'nivel_interes' => 'alto',
                'urgencia' => 'corto_plazo',
                'requiere_financiamiento' => false,
            ],
            [
                'nombre' => 'María Elena',
                'apellidos' => 'Torres Gutiérrez',
                'tipo_persona' => 'natural',
                'dni' => '78912345',
                'email' => 'maria.torres@hotmail.com',
                'celular' => '956789012',
                'direccion' => 'Jr. Las Flores 567, San Borja',
                'origen' => 'referido',
                'origen_detalle' => 'Referido por cliente Juan Pérez',
                'segmento' => 'residencial',
                'scoring' => 'A',
                'scoring_puntos' => 78,
                'estado' => 'contactado',
                'consumo_mensual_kwh' => 380,
                'factura_mensual_soles' => 280,
                'tipo_inmueble' => 'casa',
                'area_disponible_m2' => 60,
                'empresa_electrica' => 'Enel',
                'presupuesto_estimado' => 18000,
                'nivel_interes' => 'muy_alto',
                'urgencia' => 'inmediata',
                'requiere_financiamiento' => true,
            ],
            [
                'nombre' => 'Roberto',
                'apellidos' => 'Sánchez Vargas',
                'tipo_persona' => 'natural',
                'dni' => '12345678',
                'email' => 'roberto.sanchez@yahoo.com',
                'celular' => '923456789',
                'direccion' => 'Calle Los Pinos 890, Surco',
                'origen' => 'facebook',
                'origen_detalle' => 'Campaña: Ahorra con energía solar',
                'segmento' => 'residencial',
                'scoring' => 'B',
                'scoring_puntos' => 55,
                'estado' => 'nuevo',
                'consumo_mensual_kwh' => 520,
                'factura_mensual_soles' => 420,
                'tipo_inmueble' => 'casa',
                'area_disponible_m2' => 100,
                'empresa_electrica' => 'Luz del Sur',
                'presupuesto_estimado' => 35000,
                'nivel_interes' => 'medio',
                'urgencia' => 'mediano_plazo',
                'requiere_financiamiento' => true,
            ],
            
            // Prospectos Comerciales
            [
                'nombre' => 'Luis Alberto',
                'apellidos' => 'García Fernández',
                'razon_social' => 'Restaurante El Buen Sabor S.A.C.',
                'tipo_persona' => 'juridica',
                'ruc' => '20567891234',
                'email' => 'lgarcia@elbuensabor.com.pe',
                'telefono' => '012345678',
                'celular' => '945678901',
                'direccion' => 'Av. Javier Prado Este 4521, San Isidro',
                'origen' => 'llamada',
                'origen_detalle' => 'Llamó interesado después de ver letrero',
                'segmento' => 'comercial',
                'scoring' => 'A',
                'scoring_puntos' => 92,
                'estado' => 'calificado',
                'consumo_mensual_kwh' => 2500,
                'factura_mensual_soles' => 1800,
                'tipo_inmueble' => 'local_comercial',
                'area_disponible_m2' => 200,
                'tiene_medidor_bidireccional' => false,
                'empresa_electrica' => 'Enel',
                'presupuesto_estimado' => 85000,
                'nivel_interes' => 'muy_alto',
                'urgencia' => 'inmediata',
                'requiere_financiamiento' => false,
            ],
            [
                'nombre' => 'Patricia',
                'apellidos' => 'Vega Luna',
                'razon_social' => 'Clínica Dental Sonrisas E.I.R.L.',
                'tipo_persona' => 'juridica',
                'ruc' => '20456789123',
                'email' => 'patricia.vega@clinicasonrisas.com',
                'telefono' => '013456789',
                'celular' => '934567890',
                'direccion' => 'Av. Brasil 2345, Magdalena',
                'origen' => 'google_ads',
                'origen_detalle' => 'Búsqueda: paneles solares para negocio Lima',
                'segmento' => 'comercial',
                'scoring' => 'B',
                'scoring_puntos' => 65,
                'estado' => 'contactado',
                'consumo_mensual_kwh' => 1200,
                'factura_mensual_soles' => 950,
                'tipo_inmueble' => 'local_comercial',
                'area_disponible_m2' => 80,
                'empresa_electrica' => 'Enel',
                'presupuesto_estimado' => 45000,
                'nivel_interes' => 'alto',
                'urgencia' => 'corto_plazo',
                'requiere_financiamiento' => true,
            ],
            
            // Prospectos Industriales
            [
                'nombre' => 'Fernando',
                'apellidos' => 'Castillo Morales',
                'razon_social' => 'Textiles del Norte S.A.',
                'tipo_persona' => 'juridica',
                'ruc' => '20345678912',
                'email' => 'fcastillo@textilesdelnorte.com.pe',
                'telefono' => '014567891',
                'celular' => '912345678',
                'direccion' => 'Av. Industrial 567, Ate',
                'origen' => 'feria',
                'origen_detalle' => 'Expo Energía Renovable 2025',
                'segmento' => 'industrial',
                'scoring' => 'A',
                'scoring_puntos' => 95,
                'estado' => 'calificado',
                'consumo_mensual_kwh' => 15000,
                'factura_mensual_soles' => 9500,
                'tipo_inmueble' => 'fabrica',
                'area_disponible_m2' => 2000,
                'tiene_medidor_bidireccional' => true,
                'empresa_electrica' => 'Enel',
                'presupuesto_estimado' => 350000,
                'nivel_interes' => 'muy_alto',
                'urgencia' => 'corto_plazo',
                'requiere_financiamiento' => true,
            ],
            [
                'nombre' => 'Jorge',
                'apellidos' => 'Ramírez Ochoa',
                'razon_social' => 'Metalmecánica Ramírez S.A.C.',
                'tipo_persona' => 'juridica',
                'ruc' => '20234567891',
                'email' => 'jramirez@metalramirez.com',
                'telefono' => '015678912',
                'celular' => '901234567',
                'direccion' => 'Zona Industrial Ventanilla Mz. J Lt. 15',
                'origen' => 'otro',
                'origen_detalle' => 'Contacto por LinkedIn mensaje directo',
                'segmento' => 'industrial',
                'scoring' => 'B',
                'scoring_puntos' => 58,
                'estado' => 'nuevo',
                'consumo_mensual_kwh' => 8500,
                'factura_mensual_soles' => 5200,
                'tipo_inmueble' => 'fabrica',
                'area_disponible_m2' => 1200,
                'empresa_electrica' => 'Enel',
                'presupuesto_estimado' => 180000,
                'nivel_interes' => 'medio',
                'urgencia' => 'largo_plazo',
                'requiere_financiamiento' => true,
            ],
            
            // Prospectos Agrícolas
            [
                'nombre' => 'Ricardo',
                'apellidos' => 'Huamán Quispe',
                'razon_social' => 'Agrícola Huamán Hermanos',
                'tipo_persona' => 'juridica',
                'ruc' => '20123456789',
                'email' => 'rhuaman@agricolahuaman.com',
                'celular' => '956123456',
                'direccion' => 'Fundo Santa Rosa, Km 45 Panamericana Sur, Cañete',
                'origen' => 'web',
                'origen_detalle' => 'Solicitud desde landing de bombeo solar',
                'segmento' => 'agricola',
                'scoring' => 'A',
                'scoring_puntos' => 88,
                'estado' => 'contactado',
                'consumo_mensual_kwh' => 6000,
                'factura_mensual_soles' => 3800,
                'tipo_inmueble' => 'terreno_agricola',
                'area_disponible_m2' => 5000,
                'empresa_electrica' => 'Electrodunas',
                'presupuesto_estimado' => 120000,
                'nivel_interes' => 'muy_alto',
                'urgencia' => 'inmediata',
                'requiere_financiamiento' => false,
            ],
            
            // Prospectos con estados variados
            [
                'nombre' => 'Andrea',
                'apellidos' => 'López Martínez',
                'tipo_persona' => 'natural',
                'dni' => '34567891',
                'email' => 'andrea.lopez@gmail.com',
                'celular' => '978123456',
                'direccion' => 'Av. El Sol 234, Chaclacayo',
                'origen' => 'instagram',
                'segmento' => 'residencial',
                'scoring' => 'C',
                'scoring_puntos' => 35,
                'estado' => 'no_calificado',
                'consumo_mensual_kwh' => 180,
                'factura_mensual_soles' => 120,
                'tipo_inmueble' => 'departamento',
                'area_disponible_m2' => 15,
                'nivel_interes' => 'bajo',
                'urgencia' => 'largo_plazo',
                'observaciones' => 'Vive en departamento sin acceso a techo. Solo consulta informativa.',
            ],
            [
                'nombre' => 'Pedro',
                'apellidos' => 'Díaz Romero',
                'tipo_persona' => 'natural',
                'dni' => '56789123',
                'email' => 'pedro.diaz@outlook.com',
                'celular' => '967891234',
                'direccion' => 'Calle Los Álamos 567, Miraflores',
                'origen' => 'referido',
                'segmento' => 'residencial',
                'scoring' => 'B',
                'scoring_puntos' => 62,
                'estado' => 'descartado',
                'motivo_descarte' => 'Ya contrató con la competencia',
                'consumo_mensual_kwh' => 400,
                'factura_mensual_soles' => 320,
                'tipo_inmueble' => 'casa',
                'area_disponible_m2' => 50,
                'nivel_interes' => 'alto',
            ],
        ];

        foreach ($prospectos as $index => $data) {
            $codigo = 'PROSP-' . date('Y') . '-' . str_pad($index + 1, 4, '0', STR_PAD_LEFT);
            
            Prospecto::updateOrCreate(
                ['codigo' => $codigo],
                array_merge($data, [
                    'codigo' => $codigo,
                    'slug' => Str::slug($data['nombre'] . '-' . $codigo),
                    'user_id' => $vendedor?->id,
                    'fecha_primer_contacto' => now()->subDays(rand(1, 60)),
                    'fecha_ultimo_contacto' => now()->subDays(rand(0, 15)),
                    'fecha_proximo_contacto' => now()->addDays(rand(1, 14)),
                ])
            );
        }
    }
}
