<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class UbigeoSeeder extends Seeder
{
    /**
     * Seeder para Departamentos, Provincias y Distritos del Perú
     * Cubre todos los departamentos, todas sus provincias y sus distritos completos.
     */
    public function run(): void
    {
        // =====================================================
        // DEPARTAMENTOS
        // =====================================================
        $departamentos = [
            ['codigo' => '01', 'nombre' => 'Amazonas'],
            ['codigo' => '02', 'nombre' => 'Áncash'],
            ['codigo' => '03', 'nombre' => 'Apurímac'],
            ['codigo' => '04', 'nombre' => 'Arequipa'],
            ['codigo' => '05', 'nombre' => 'Ayacucho'],
            ['codigo' => '06', 'nombre' => 'Cajamarca'],
            ['codigo' => '07', 'nombre' => 'Callao'],
            ['codigo' => '08', 'nombre' => 'Cusco'],
            ['codigo' => '09', 'nombre' => 'Huancavelica'],
            ['codigo' => '10', 'nombre' => 'Huánuco'],
            ['codigo' => '11', 'nombre' => 'Ica'],
            ['codigo' => '12', 'nombre' => 'Junín'],
            ['codigo' => '13', 'nombre' => 'La Libertad'],
            ['codigo' => '14', 'nombre' => 'Lambayeque'],
            ['codigo' => '15', 'nombre' => 'Lima'],
            ['codigo' => '16', 'nombre' => 'Loreto'],
            ['codigo' => '17', 'nombre' => 'Madre de Dios'],
            ['codigo' => '18', 'nombre' => 'Moquegua'],
            ['codigo' => '19', 'nombre' => 'Pasco'],
            ['codigo' => '20', 'nombre' => 'Piura'],
            ['codigo' => '21', 'nombre' => 'Puno'],
            ['codigo' => '22', 'nombre' => 'San Martín'],
            ['codigo' => '23', 'nombre' => 'Tacna'],
            ['codigo' => '24', 'nombre' => 'Tumbes'],
            ['codigo' => '25', 'nombre' => 'Ucayali'],
        ];

        foreach ($departamentos as $depto) {
            DB::table('departamentos')->insert([
                'codigo'     => $depto['codigo'],
                'nombre'     => $depto['nombre'],
                'slug'       => Str::slug($depto['nombre']),
                'activo'     => true,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }

        // =====================================================
        // PROVINCIAS (todas las del Perú)
        // =====================================================
        $provincias = [
            // Amazonas
            ['codigo' => '0101', 'nombre' => 'Chachapoyas',     'dep' => '01'],
            ['codigo' => '0102', 'nombre' => 'Bagua',           'dep' => '01'],
            ['codigo' => '0103', 'nombre' => 'Bongará',         'dep' => '01'],
            ['codigo' => '0104', 'nombre' => 'Condorcanqui',    'dep' => '01'],
            ['codigo' => '0105', 'nombre' => 'Luya',            'dep' => '01'],
            ['codigo' => '0106', 'nombre' => 'Rodríguez de Mendoza', 'dep' => '01'],
            ['codigo' => '0107', 'nombre' => 'Utcubamba',       'dep' => '01'],
            // Áncash
            ['codigo' => '0201', 'nombre' => 'Huaraz',          'dep' => '02'],
            ['codigo' => '0202', 'nombre' => 'Aija',            'dep' => '02'],
            ['codigo' => '0203', 'nombre' => 'Antonio Raimondi','dep' => '02'],
            ['codigo' => '0204', 'nombre' => 'Asunción',        'dep' => '02'],
            ['codigo' => '0205', 'nombre' => 'Bolognesi',       'dep' => '02'],
            ['codigo' => '0206', 'nombre' => 'Carhuaz',         'dep' => '02'],
            ['codigo' => '0207', 'nombre' => 'Carlos Fermín Fitzcarrald', 'dep' => '02'],
            ['codigo' => '0208', 'nombre' => 'Casma',           'dep' => '02'],
            ['codigo' => '0209', 'nombre' => 'Corongo',         'dep' => '02'],
            ['codigo' => '0210', 'nombre' => 'Huari',           'dep' => '02'],
            ['codigo' => '0211', 'nombre' => 'Huarmey',         'dep' => '02'],
            ['codigo' => '0212', 'nombre' => 'Huaylas',         'dep' => '02'],
            ['codigo' => '0213', 'nombre' => 'Mariscal Luzuriaga', 'dep' => '02'],
            ['codigo' => '0214', 'nombre' => 'Ocros',           'dep' => '02'],
            ['codigo' => '0215', 'nombre' => 'Pallasca',        'dep' => '02'],
            ['codigo' => '0216', 'nombre' => 'Pomabamba',       'dep' => '02'],
            ['codigo' => '0217', 'nombre' => 'Recuay',          'dep' => '02'],
            ['codigo' => '0218', 'nombre' => 'Santa',           'dep' => '02'],
            ['codigo' => '0219', 'nombre' => 'Sihuas',          'dep' => '02'],
            ['codigo' => '0220', 'nombre' => 'Yungay',          'dep' => '02'],
            // Apurímac
            ['codigo' => '0301', 'nombre' => 'Abancay',         'dep' => '03'],
            ['codigo' => '0302', 'nombre' => 'Andahuaylas',     'dep' => '03'],
            ['codigo' => '0303', 'nombre' => 'Antabamba',       'dep' => '03'],
            ['codigo' => '0304', 'nombre' => 'Aymaraes',        'dep' => '03'],
            ['codigo' => '0305', 'nombre' => 'Cotabambas',      'dep' => '03'],
            ['codigo' => '0306', 'nombre' => 'Chincheros',      'dep' => '03'],
            ['codigo' => '0307', 'nombre' => 'Grau',            'dep' => '03'],
            // Arequipa
            ['codigo' => '0401', 'nombre' => 'Arequipa',        'dep' => '04'],
            ['codigo' => '0402', 'nombre' => 'Camaná',          'dep' => '04'],
            ['codigo' => '0403', 'nombre' => 'Caravelí',        'dep' => '04'],
            ['codigo' => '0404', 'nombre' => 'Castilla',        'dep' => '04'],
            ['codigo' => '0405', 'nombre' => 'Caylloma',        'dep' => '04'],
            ['codigo' => '0406', 'nombre' => 'Condesuyos',      'dep' => '04'],
            ['codigo' => '0407', 'nombre' => 'Islay',           'dep' => '04'],
            ['codigo' => '0408', 'nombre' => 'La Unión',        'dep' => '04'],
            // Ayacucho
            ['codigo' => '0501', 'nombre' => 'Huamanga',        'dep' => '05'],
            ['codigo' => '0502', 'nombre' => 'Cangallo',        'dep' => '05'],
            ['codigo' => '0503', 'nombre' => 'Huanca Sancos',   'dep' => '05'],
            ['codigo' => '0504', 'nombre' => 'Huanta',          'dep' => '05'],
            ['codigo' => '0505', 'nombre' => 'La Mar',          'dep' => '05'],
            ['codigo' => '0506', 'nombre' => 'Lucanas',         'dep' => '05'],
            ['codigo' => '0507', 'nombre' => 'Parinacochas',    'dep' => '05'],
            ['codigo' => '0508', 'nombre' => 'Páucar del Sara Sara', 'dep' => '05'],
            ['codigo' => '0509', 'nombre' => 'Sucre',           'dep' => '05'],
            ['codigo' => '0510', 'nombre' => 'Víctor Fajardo',  'dep' => '05'],
            ['codigo' => '0511', 'nombre' => 'Vilcas Huamán',   'dep' => '05'],
            // Cajamarca
            ['codigo' => '0601', 'nombre' => 'Cajamarca',       'dep' => '06'],
            ['codigo' => '0602', 'nombre' => 'Cajabamba',       'dep' => '06'],
            ['codigo' => '0603', 'nombre' => 'Celendín',        'dep' => '06'],
            ['codigo' => '0604', 'nombre' => 'Chota',           'dep' => '06'],
            ['codigo' => '0605', 'nombre' => 'Contumazá',       'dep' => '06'],
            ['codigo' => '0606', 'nombre' => 'Cutervo',         'dep' => '06'],
            ['codigo' => '0607', 'nombre' => 'Hualgayoc',       'dep' => '06'],
            ['codigo' => '0608', 'nombre' => 'Jaén',            'dep' => '06'],
            ['codigo' => '0609', 'nombre' => 'San Ignacio',     'dep' => '06'],
            ['codigo' => '0610', 'nombre' => 'San Marcos',      'dep' => '06'],
            ['codigo' => '0611', 'nombre' => 'San Miguel',      'dep' => '06'],
            ['codigo' => '0612', 'nombre' => 'San Pablo',       'dep' => '06'],
            ['codigo' => '0613', 'nombre' => 'Santa Cruz',      'dep' => '06'],
            // Callao
            ['codigo' => '0701', 'nombre' => 'Callao',          'dep' => '07'],
            // Cusco
            ['codigo' => '0801', 'nombre' => 'Cusco',           'dep' => '08'],
            ['codigo' => '0802', 'nombre' => 'Acomayo',         'dep' => '08'],
            ['codigo' => '0803', 'nombre' => 'Anta',            'dep' => '08'],
            ['codigo' => '0804', 'nombre' => 'Calca',           'dep' => '08'],
            ['codigo' => '0805', 'nombre' => 'Canas',           'dep' => '08'],
            ['codigo' => '0806', 'nombre' => 'Canchis',         'dep' => '08'],
            ['codigo' => '0807', 'nombre' => 'Chumbivilcas',    'dep' => '08'],
            ['codigo' => '0808', 'nombre' => 'Espinar',         'dep' => '08'],
            ['codigo' => '0809', 'nombre' => 'La Convención',   'dep' => '08'],
            ['codigo' => '0810', 'nombre' => 'Paruro',          'dep' => '08'],
            ['codigo' => '0811', 'nombre' => 'Paucartambo',     'dep' => '08'],
            ['codigo' => '0812', 'nombre' => 'Quispicanchis',   'dep' => '08'],
            ['codigo' => '0813', 'nombre' => 'Urubamba',        'dep' => '08'],
            // Huancavelica
            ['codigo' => '0901', 'nombre' => 'Huancavelica',    'dep' => '09'],
            ['codigo' => '0902', 'nombre' => 'Acobamba',        'dep' => '09'],
            ['codigo' => '0903', 'nombre' => 'Angaraes',        'dep' => '09'],
            ['codigo' => '0904', 'nombre' => 'Castrovirreyna',  'dep' => '09'],
            ['codigo' => '0905', 'nombre' => 'Churcampa',       'dep' => '09'],
            ['codigo' => '0906', 'nombre' => 'Huaytará',        'dep' => '09'],
            ['codigo' => '0907', 'nombre' => 'Tayacaja',        'dep' => '09'],
            // Huánuco
            ['codigo' => '1001', 'nombre' => 'Huánuco',         'dep' => '10'],
            ['codigo' => '1002', 'nombre' => 'Ambo',            'dep' => '10'],
            ['codigo' => '1003', 'nombre' => 'Dos de Mayo',     'dep' => '10'],
            ['codigo' => '1004', 'nombre' => 'Huacaybamba',     'dep' => '10'],
            ['codigo' => '1005', 'nombre' => 'Huamalíes',       'dep' => '10'],
            ['codigo' => '1006', 'nombre' => 'Leoncio Prado',   'dep' => '10'],
            ['codigo' => '1007', 'nombre' => 'Marañón',         'dep' => '10'],
            ['codigo' => '1008', 'nombre' => 'Pachitea',        'dep' => '10'],
            ['codigo' => '1009', 'nombre' => 'Puerto Inca',     'dep' => '10'],
            ['codigo' => '1010', 'nombre' => 'Lauricocha',      'dep' => '10'],
            ['codigo' => '1011', 'nombre' => 'Yarowilca',       'dep' => '10'],
            // Ica
            ['codigo' => '1101', 'nombre' => 'Ica',             'dep' => '11'],
            ['codigo' => '1102', 'nombre' => 'Chincha',         'dep' => '11'],
            ['codigo' => '1103', 'nombre' => 'Nazca',           'dep' => '11'],
            ['codigo' => '1104', 'nombre' => 'Palpa',           'dep' => '11'],
            ['codigo' => '1105', 'nombre' => 'Pisco',           'dep' => '11'],
            // Junín
            ['codigo' => '1201', 'nombre' => 'Huancayo',        'dep' => '12'],
            ['codigo' => '1202', 'nombre' => 'Concepción',      'dep' => '12'],
            ['codigo' => '1203', 'nombre' => 'Chanchamayo',     'dep' => '12'],
            ['codigo' => '1204', 'nombre' => 'Junín',           'dep' => '12'],
            ['codigo' => '1205', 'nombre' => 'Satipo',          'dep' => '12'],
            ['codigo' => '1206', 'nombre' => 'Tarma',           'dep' => '12'],
            ['codigo' => '1207', 'nombre' => 'Yauli',           'dep' => '12'],
            ['codigo' => '1208', 'nombre' => 'Chupaca',         'dep' => '12'],
            // La Libertad
            ['codigo' => '1301', 'nombre' => 'Trujillo',        'dep' => '13'],
            ['codigo' => '1302', 'nombre' => 'Ascope',          'dep' => '13'],
            ['codigo' => '1303', 'nombre' => 'Bolívar',         'dep' => '13'],
            ['codigo' => '1304', 'nombre' => 'Chepén',          'dep' => '13'],
            ['codigo' => '1305', 'nombre' => 'Julcán',          'dep' => '13'],
            ['codigo' => '1306', 'nombre' => 'Otuzco',          'dep' => '13'],
            ['codigo' => '1307', 'nombre' => 'Pacasmayo',       'dep' => '13'],
            ['codigo' => '1308', 'nombre' => 'Pataz',           'dep' => '13'],
            ['codigo' => '1309', 'nombre' => 'Sánchez Carrión', 'dep' => '13'],
            ['codigo' => '1310', 'nombre' => 'Santiago de Chuco', 'dep' => '13'],
            ['codigo' => '1311', 'nombre' => 'Gran Chimú',      'dep' => '13'],
            ['codigo' => '1312', 'nombre' => 'Virú',            'dep' => '13'],
            // Lambayeque
            ['codigo' => '1401', 'nombre' => 'Chiclayo',        'dep' => '14'],
            ['codigo' => '1402', 'nombre' => 'Ferreñafe',       'dep' => '14'],
            ['codigo' => '1403', 'nombre' => 'Lambayeque',      'dep' => '14'],
            // Lima
            ['codigo' => '1501', 'nombre' => 'Lima',            'dep' => '15'],
            ['codigo' => '1502', 'nombre' => 'Barranca',        'dep' => '15'],
            ['codigo' => '1503', 'nombre' => 'Cajatambo',       'dep' => '15'],
            ['codigo' => '1504', 'nombre' => 'Canta',           'dep' => '15'],
            ['codigo' => '1505', 'nombre' => 'Cañete',          'dep' => '15'],
            ['codigo' => '1506', 'nombre' => 'Huaral',          'dep' => '15'],
            ['codigo' => '1507', 'nombre' => 'Huarochirí',      'dep' => '15'],
            ['codigo' => '1508', 'nombre' => 'Huaura',          'dep' => '15'],
            ['codigo' => '1509', 'nombre' => 'Oyón',            'dep' => '15'],
            ['codigo' => '1510', 'nombre' => 'Yauyos',          'dep' => '15'],
            // Loreto
            ['codigo' => '1601', 'nombre' => 'Maynas',          'dep' => '16'],
            ['codigo' => '1602', 'nombre' => 'Alto Amazonas',   'dep' => '16'],
            ['codigo' => '1603', 'nombre' => 'Loreto',          'dep' => '16'],
            ['codigo' => '1604', 'nombre' => 'Mariscal Ramón Castilla', 'dep' => '16'],
            ['codigo' => '1605', 'nombre' => 'Putumayo',        'dep' => '16'],
            ['codigo' => '1606', 'nombre' => 'Requena',         'dep' => '16'],
            ['codigo' => '1607', 'nombre' => 'Ucayali',         'dep' => '16'],
            ['codigo' => '1608', 'nombre' => 'Datem del Marañón', 'dep' => '16'],
            ['codigo' => '1609', 'nombre' => 'Kuélap',          'dep' => '16'],
            // Madre de Dios
            ['codigo' => '1701', 'nombre' => 'Tambopata',       'dep' => '17'],
            ['codigo' => '1702', 'nombre' => 'Manu',            'dep' => '17'],
            ['codigo' => '1703', 'nombre' => 'Tahuamanu',       'dep' => '17'],
            // Moquegua
            ['codigo' => '1801', 'nombre' => 'Mariscal Nieto',  'dep' => '18'],
            ['codigo' => '1802', 'nombre' => 'General Sánchez Cerro', 'dep' => '18'],
            ['codigo' => '1803', 'nombre' => 'Ilo',             'dep' => '18'],
            // Pasco
            ['codigo' => '1901', 'nombre' => 'Pasco',           'dep' => '19'],
            ['codigo' => '1902', 'nombre' => 'Daniel Alcides Carrión', 'dep' => '19'],
            ['codigo' => '1903', 'nombre' => 'Oxapampa',        'dep' => '19'],
            // Piura
            ['codigo' => '2001', 'nombre' => 'Piura',           'dep' => '20'],
            ['codigo' => '2002', 'nombre' => 'Ayabaca',         'dep' => '20'],
            ['codigo' => '2003', 'nombre' => 'Huancabamba',     'dep' => '20'],
            ['codigo' => '2004', 'nombre' => 'Morropón',        'dep' => '20'],
            ['codigo' => '2005', 'nombre' => 'Paita',           'dep' => '20'],
            ['codigo' => '2006', 'nombre' => 'Sullana',         'dep' => '20'],
            ['codigo' => '2007', 'nombre' => 'Talara',          'dep' => '20'],
            ['codigo' => '2008', 'nombre' => 'Sechura',         'dep' => '20'],
            // Puno
            ['codigo' => '2101', 'nombre' => 'Puno',            'dep' => '21'],
            ['codigo' => '2102', 'nombre' => 'Azángaro',        'dep' => '21'],
            ['codigo' => '2103', 'nombre' => 'Carabaya',        'dep' => '21'],
            ['codigo' => '2104', 'nombre' => 'Chucuito',        'dep' => '21'],
            ['codigo' => '2105', 'nombre' => 'El Collao',       'dep' => '21'],
            ['codigo' => '2106', 'nombre' => 'Huancané',        'dep' => '21'],
            ['codigo' => '2107', 'nombre' => 'Lampa',           'dep' => '21'],
            ['codigo' => '2108', 'nombre' => 'Melgar',          'dep' => '21'],
            ['codigo' => '2109', 'nombre' => 'Moho',            'dep' => '21'],
            ['codigo' => '2110', 'nombre' => 'San Antonio de Putina', 'dep' => '21'],
            ['codigo' => '2111', 'nombre' => 'San Román',       'dep' => '21'],
            ['codigo' => '2112', 'nombre' => 'Sandia',          'dep' => '21'],
            ['codigo' => '2113', 'nombre' => 'Yunguyo',         'dep' => '21'],
            // San Martín
            ['codigo' => '2201', 'nombre' => 'Moyobamba',       'dep' => '22'],
            ['codigo' => '2202', 'nombre' => 'Bellavista',      'dep' => '22'],
            ['codigo' => '2203', 'nombre' => 'El Dorado',       'dep' => '22'],
            ['codigo' => '2204', 'nombre' => 'Huallaga',        'dep' => '22'],
            ['codigo' => '2205', 'nombre' => 'Lamas',           'dep' => '22'],
            ['codigo' => '2206', 'nombre' => 'Mariscal Cáceres','dep' => '22'],
            ['codigo' => '2207', 'nombre' => 'Picota',          'dep' => '22'],
            ['codigo' => '2208', 'nombre' => 'Rioja',           'dep' => '22'],
            ['codigo' => '2209', 'nombre' => 'San Martín',      'dep' => '22'],
            ['codigo' => '2210', 'nombre' => 'Tocache',         'dep' => '22'],
            // Tacna
            ['codigo' => '2301', 'nombre' => 'Tacna',           'dep' => '23'],
            ['codigo' => '2302', 'nombre' => 'Candarave',       'dep' => '23'],
            ['codigo' => '2303', 'nombre' => 'Jorge Basadre',   'dep' => '23'],
            ['codigo' => '2304', 'nombre' => 'Tarata',          'dep' => '23'],
            // Tumbes
            ['codigo' => '2401', 'nombre' => 'Tumbes',          'dep' => '24'],
            ['codigo' => '2402', 'nombre' => 'Contralmirante Villar', 'dep' => '24'],
            ['codigo' => '2403', 'nombre' => 'Zarumilla',       'dep' => '24'],
            // Ucayali
            ['codigo' => '2501', 'nombre' => 'Coronel Portillo','dep' => '25'],
            ['codigo' => '2502', 'nombre' => 'Atalaya',         'dep' => '25'],
            ['codigo' => '2503', 'nombre' => 'Padre Abad',      'dep' => '25'],
            ['codigo' => '2504', 'nombre' => 'Purús',           'dep' => '25'],
        ];

        foreach ($provincias as $prov) {
            $depId = DB::table('departamentos')->where('codigo', $prov['dep'])->value('id');
            DB::table('provincias')->insert([
                'codigo'          => $prov['codigo'],
                'nombre'          => $prov['nombre'],
                'slug'            => Str::slug($prov['nombre']),
                'departamento_id' => $depId,
                'activo'          => true,
                'created_at'      => now(),
                'updated_at'      => now(),
            ]);
        }

        // =====================================================
        // DISTRITOS (todas las provincias cargadas)
        // =====================================================
        $distritos = [
            // ---- CALLAO ----
            ['codigo' => '070101', 'nombre' => 'Callao',                          'prov' => '0701'],
            ['codigo' => '070102', 'nombre' => 'Bellavista',                      'prov' => '0701'],
            ['codigo' => '070103', 'nombre' => 'Carmen de La Legua Reynoso',      'prov' => '0701'],
            ['codigo' => '070104', 'nombre' => 'La Perla',                        'prov' => '0701'],
            ['codigo' => '070105', 'nombre' => 'La Punta',                        'prov' => '0701'],
            ['codigo' => '070106', 'nombre' => 'Ventanilla',                      'prov' => '0701'],
            ['codigo' => '070107', 'nombre' => 'Mi Perú',                         'prov' => '0701'],

            // ---- LIMA ----
            ['codigo' => '150101', 'nombre' => 'Lima',                            'prov' => '1501'],
            ['codigo' => '150102', 'nombre' => 'Ancón',                           'prov' => '1501'],
            ['codigo' => '150103', 'nombre' => 'Ate',                             'prov' => '1501'],
            ['codigo' => '150104', 'nombre' => 'Barranco',                        'prov' => '1501'],
            ['codigo' => '150105', 'nombre' => 'Breña',                           'prov' => '1501'],
            ['codigo' => '150106', 'nombre' => 'Carabayllo',                      'prov' => '1501'],
            ['codigo' => '150107', 'nombre' => 'Chaclacayo',                      'prov' => '1501'],
            ['codigo' => '150108', 'nombre' => 'Chorrillos',                      'prov' => '1501'],
            ['codigo' => '150109', 'nombre' => 'Cieneguilla',                     'prov' => '1501'],
            ['codigo' => '150110', 'nombre' => 'Comas',                           'prov' => '1501'],
            ['codigo' => '150111', 'nombre' => 'El Agustino',                     'prov' => '1501'],
            ['codigo' => '150112', 'nombre' => 'Independencia',                   'prov' => '1501'],
            ['codigo' => '150113', 'nombre' => 'Jesús María',                     'prov' => '1501'],
            ['codigo' => '150114', 'nombre' => 'La Molina',                       'prov' => '1501'],
            ['codigo' => '150115', 'nombre' => 'La Victoria',                     'prov' => '1501'],
            ['codigo' => '150116', 'nombre' => 'Lince',                           'prov' => '1501'],
            ['codigo' => '150117', 'nombre' => 'Los Olivos',                      'prov' => '1501'],
            ['codigo' => '150118', 'nombre' => 'Lurigancho',                      'prov' => '1501'],
            ['codigo' => '150119', 'nombre' => 'Lurín',                           'prov' => '1501'],
            ['codigo' => '150120', 'nombre' => 'Magdalena del Mar',               'prov' => '1501'],
            ['codigo' => '150121', 'nombre' => 'Pueblo Libre',                    'prov' => '1501'],
            ['codigo' => '150122', 'nombre' => 'Miraflores',                      'prov' => '1501'],
            ['codigo' => '150123', 'nombre' => 'Pachacámac',                      'prov' => '1501'],
            ['codigo' => '150124', 'nombre' => 'Pucusana',                        'prov' => '1501'],
            ['codigo' => '150125', 'nombre' => 'Puente Piedra',                   'prov' => '1501'],
            ['codigo' => '150126', 'nombre' => 'Punta Hermosa',                   'prov' => '1501'],
            ['codigo' => '150127', 'nombre' => 'Punta Negra',                     'prov' => '1501'],
            ['codigo' => '150128', 'nombre' => 'Rímac',                           'prov' => '1501'],
            ['codigo' => '150129', 'nombre' => 'San Bartolo',                     'prov' => '1501'],
            ['codigo' => '150130', 'nombre' => 'San Borja',                       'prov' => '1501'],
            ['codigo' => '150131', 'nombre' => 'San Isidro',                      'prov' => '1501'],
            ['codigo' => '150132', 'nombre' => 'San Juan de Lurigancho',          'prov' => '1501'],
            ['codigo' => '150133', 'nombre' => 'San Juan de Miraflores',          'prov' => '1501'],
            ['codigo' => '150134', 'nombre' => 'San Luis',                        'prov' => '1501'],
            ['codigo' => '150135', 'nombre' => 'San Martín de Porres',            'prov' => '1501'],
            ['codigo' => '150136', 'nombre' => 'San Miguel',                      'prov' => '1501'],
            ['codigo' => '150137', 'nombre' => 'Santa Anita',                     'prov' => '1501'],
            ['codigo' => '150138', 'nombre' => 'Santa María del Mar',             'prov' => '1501'],
            ['codigo' => '150139', 'nombre' => 'Santa Rosa',                      'prov' => '1501'],
            ['codigo' => '150140', 'nombre' => 'Santiago de Surco',               'prov' => '1501'],
            ['codigo' => '150141', 'nombre' => 'Surquillo',                       'prov' => '1501'],
            ['codigo' => '150142', 'nombre' => 'Villa El Salvador',               'prov' => '1501'],
            ['codigo' => '150143', 'nombre' => 'Villa María del Triunfo',         'prov' => '1501'],
            // Lima - Barranca
            ['codigo' => '150201', 'nombre' => 'Barranca',                        'prov' => '1502'],
            ['codigo' => '150202', 'nombre' => 'Paramonga',                       'prov' => '1502'],
            ['codigo' => '150203', 'nombre' => 'Pativilca',                       'prov' => '1502'],
            ['codigo' => '150204', 'nombre' => 'Supe',                            'prov' => '1502'],
            ['codigo' => '150205', 'nombre' => 'Supe Puerto',                     'prov' => '1502'],
            // Lima - Cañete
            ['codigo' => '150501', 'nombre' => 'San Vicente de Cañete',           'prov' => '1505'],
            ['codigo' => '150502', 'nombre' => 'Asia',                            'prov' => '1505'],
            ['codigo' => '150503', 'nombre' => 'Calango',                         'prov' => '1505'],
            ['codigo' => '150504', 'nombre' => 'Cerro Azul',                      'prov' => '1505'],
            ['codigo' => '150505', 'nombre' => 'Chilca',                          'prov' => '1505'],
            ['codigo' => '150506', 'nombre' => 'Coayllo',                         'prov' => '1505'],
            ['codigo' => '150507', 'nombre' => 'Imperial',                        'prov' => '1505'],
            ['codigo' => '150508', 'nombre' => 'Lunahuaná',                       'prov' => '1505'],
            ['codigo' => '150509', 'nombre' => 'Mala',                            'prov' => '1505'],
            ['codigo' => '150510', 'nombre' => 'Nuevo Imperial',                  'prov' => '1505'],
            ['codigo' => '150511', 'nombre' => 'Quilmaná',                        'prov' => '1505'],
            ['codigo' => '150512', 'nombre' => 'San Antonio',                     'prov' => '1505'],
            ['codigo' => '150513', 'nombre' => 'San Luis',                        'prov' => '1505'],
            ['codigo' => '150514', 'nombre' => 'Santa Cruz de Flores',            'prov' => '1505'],
            ['codigo' => '150515', 'nombre' => 'Zúñiga',                          'prov' => '1505'],
            // Lima - Huaral
            ['codigo' => '150601', 'nombre' => 'Huaral',                          'prov' => '1506'],
            ['codigo' => '150602', 'nombre' => 'Atavillos Alto',                  'prov' => '1506'],
            ['codigo' => '150603', 'nombre' => 'Atavillos Bajo',                  'prov' => '1506'],
            ['codigo' => '150604', 'nombre' => 'Chancay',                         'prov' => '1506'],
            ['codigo' => '150605', 'nombre' => 'Ihuarí',                          'prov' => '1506'],
            ['codigo' => '150606', 'nombre' => 'Lampián',                         'prov' => '1506'],
            ['codigo' => '150607', 'nombre' => 'Pacaraos',                        'prov' => '1506'],
            ['codigo' => '150608', 'nombre' => 'San Miguel de Acos',              'prov' => '1506'],
            ['codigo' => '150609', 'nombre' => 'Santa Cruz de Andamarca',         'prov' => '1506'],
            ['codigo' => '150610', 'nombre' => 'Sumbilca',                        'prov' => '1506'],
            ['codigo' => '150611', 'nombre' => 'Veintisiete de Noviembre',        'prov' => '1506'],
            // Lima - Huaura
            ['codigo' => '150801', 'nombre' => 'Huacho',                          'prov' => '1508'],
            ['codigo' => '150802', 'nombre' => 'Ambar',                           'prov' => '1508'],
            ['codigo' => '150803', 'nombre' => 'Caleta de Carquín',               'prov' => '1508'],
            ['codigo' => '150804', 'nombre' => 'Checras',                         'prov' => '1508'],
            ['codigo' => '150805', 'nombre' => 'Hualmay',                         'prov' => '1508'],
            ['codigo' => '150806', 'nombre' => 'Huaura',                          'prov' => '1508'],
            ['codigo' => '150807', 'nombre' => 'Leoncio Prado',                   'prov' => '1508'],
            ['codigo' => '150808', 'nombre' => 'Paccho',                          'prov' => '1508'],
            ['codigo' => '150809', 'nombre' => 'Santa Leonor',                    'prov' => '1508'],
            ['codigo' => '150810', 'nombre' => 'Santa María',                     'prov' => '1508'],
            ['codigo' => '150811', 'nombre' => 'Sayan',                           'prov' => '1508'],
            ['codigo' => '150812', 'nombre' => 'Vegueta',                         'prov' => '1508'],

            // ---- ICA ----
            ['codigo' => '110101', 'nombre' => 'Ica',                             'prov' => '1101'],
            ['codigo' => '110102', 'nombre' => 'La Tinguiña',                     'prov' => '1101'],
            ['codigo' => '110103', 'nombre' => 'Los Aquijes',                     'prov' => '1101'],
            ['codigo' => '110104', 'nombre' => 'Ocucaje',                         'prov' => '1101'],
            ['codigo' => '110105', 'nombre' => 'Pachacútec',                      'prov' => '1101'],
            ['codigo' => '110106', 'nombre' => 'Parcona',                         'prov' => '1101'],
            ['codigo' => '110107', 'nombre' => 'Pueblo Nuevo',                    'prov' => '1101'],
            ['codigo' => '110108', 'nombre' => 'Salas',                           'prov' => '1101'],
            ['codigo' => '110109', 'nombre' => 'San José de Los Molinos',         'prov' => '1101'],
            ['codigo' => '110110', 'nombre' => 'San Juan Bautista',               'prov' => '1101'],
            ['codigo' => '110111', 'nombre' => 'Santiago',                        'prov' => '1101'],
            ['codigo' => '110112', 'nombre' => 'Subtanjalla',                     'prov' => '1101'],
            ['codigo' => '110113', 'nombre' => 'Tate',                            'prov' => '1101'],
            ['codigo' => '110114', 'nombre' => 'Yauca del Rosario',               'prov' => '1101'],
            // Ica - Chincha
            ['codigo' => '110201', 'nombre' => 'Chincha Alta',                    'prov' => '1102'],
            ['codigo' => '110202', 'nombre' => 'Alto Larán',                      'prov' => '1102'],
            ['codigo' => '110203', 'nombre' => 'Chavín',                          'prov' => '1102'],
            ['codigo' => '110204', 'nombre' => 'El Carmen',                       'prov' => '1102'],
            ['codigo' => '110205', 'nombre' => 'Grocio Prado',                    'prov' => '1102'],
            ['codigo' => '110206', 'nombre' => 'Pueblo Nuevo',                    'prov' => '1102'],
            ['codigo' => '110207', 'nombre' => 'San Juan de Yanac',               'prov' => '1102'],
            ['codigo' => '110208', 'nombre' => 'San Pedro de Huacarpana',         'prov' => '1102'],
            ['codigo' => '110209', 'nombre' => 'Sunampe',                         'prov' => '1102'],
            ['codigo' => '110210', 'nombre' => 'Tambo de Mora',                   'prov' => '1102'],
            // Ica - Nazca
            ['codigo' => '110301', 'nombre' => 'Nazca',                           'prov' => '1103'],
            ['codigo' => '110302', 'nombre' => 'Changuillo',                      'prov' => '1103'],
            ['codigo' => '110303', 'nombre' => 'El Ingenio',                      'prov' => '1103'],
            ['codigo' => '110304', 'nombre' => 'Marcona',                         'prov' => '1103'],
            ['codigo' => '110305', 'nombre' => 'Vista Alegre',                    'prov' => '1103'],
            // Ica - Palpa
            ['codigo' => '110401', 'nombre' => 'Palpa',                           'prov' => '1104'],
            ['codigo' => '110402', 'nombre' => 'Llipata',                         'prov' => '1104'],
            ['codigo' => '110403', 'nombre' => 'Río Grande',                      'prov' => '1104'],
            ['codigo' => '110404', 'nombre' => 'Santa Cruz',                      'prov' => '1104'],
            ['codigo' => '110405', 'nombre' => 'Tibillo',                         'prov' => '1104'],
            // Ica - Pisco
            ['codigo' => '110501', 'nombre' => 'Pisco',                           'prov' => '1105'],
            ['codigo' => '110502', 'nombre' => 'Huancano',                        'prov' => '1105'],
            ['codigo' => '110503', 'nombre' => 'Humay',                           'prov' => '1105'],
            ['codigo' => '110504', 'nombre' => 'Independencia',                   'prov' => '1105'],
            ['codigo' => '110505', 'nombre' => 'Paracas',                         'prov' => '1105'],
            ['codigo' => '110506', 'nombre' => 'San Andrés',                      'prov' => '1105'],
            ['codigo' => '110507', 'nombre' => 'San Clemente',                    'prov' => '1105'],
            ['codigo' => '110508', 'nombre' => 'Túpac Amaru Inca',                'prov' => '1105'],

            // ---- AREQUIPA ----
            ['codigo' => '040101', 'nombre' => 'Arequipa',                        'prov' => '0401'],
            ['codigo' => '040102', 'nombre' => 'Alto Selva Alegre',               'prov' => '0401'],
            ['codigo' => '040103', 'nombre' => 'Cayma',                           'prov' => '0401'],
            ['codigo' => '040104', 'nombre' => 'Cerro Colorado',                  'prov' => '0401'],
            ['codigo' => '040105', 'nombre' => 'Characato',                       'prov' => '0401'],
            ['codigo' => '040106', 'nombre' => 'Chiguata',                        'prov' => '0401'],
            ['codigo' => '040107', 'nombre' => 'Jacobo Hunter',                   'prov' => '0401'],
            ['codigo' => '040108', 'nombre' => 'José Luis Bustamante y Rivero',   'prov' => '0401'],
            ['codigo' => '040109', 'nombre' => 'La Joya',                         'prov' => '0401'],
            ['codigo' => '040110', 'nombre' => 'Mariano Melgar',                  'prov' => '0401'],
            ['codigo' => '040111', 'nombre' => 'Miraflores',                      'prov' => '0401'],
            ['codigo' => '040112', 'nombre' => 'Mollebaya',                       'prov' => '0401'],
            ['codigo' => '040113', 'nombre' => 'Paucarpata',                      'prov' => '0401'],
            ['codigo' => '040114', 'nombre' => 'Pocsi',                           'prov' => '0401'],
            ['codigo' => '040115', 'nombre' => 'Polobaya',                        'prov' => '0401'],
            ['codigo' => '040116', 'nombre' => 'Quequeña',                        'prov' => '0401'],
            ['codigo' => '040117', 'nombre' => 'Sabandía',                        'prov' => '0401'],
            ['codigo' => '040118', 'nombre' => 'Sachaca',                         'prov' => '0401'],
            ['codigo' => '040119', 'nombre' => 'San Juan de Siguas',              'prov' => '0401'],
            ['codigo' => '040120', 'nombre' => 'San Juan de Tarucani',            'prov' => '0401'],
            ['codigo' => '040121', 'nombre' => 'Santa Isabel de Siguas',          'prov' => '0401'],
            ['codigo' => '040122', 'nombre' => 'Santa Rita de Siguas',            'prov' => '0401'],
            ['codigo' => '040123', 'nombre' => 'Socabaya',                        'prov' => '0401'],
            ['codigo' => '040124', 'nombre' => 'Tiabaya',                         'prov' => '0401'],
            ['codigo' => '040125', 'nombre' => 'Uchumayo',                        'prov' => '0401'],
            ['codigo' => '040126', 'nombre' => 'Vitor',                           'prov' => '0401'],
            ['codigo' => '040127', 'nombre' => 'Yanahuara',                       'prov' => '0401'],
            ['codigo' => '040128', 'nombre' => 'Yarabamba',                       'prov' => '0401'],
            ['codigo' => '040129', 'nombre' => 'Yura',                            'prov' => '0401'],
            // Arequipa - Camaná
            ['codigo' => '040201', 'nombre' => 'Camaná',                          'prov' => '0402'],
            ['codigo' => '040202', 'nombre' => 'José María Quimper',              'prov' => '0402'],
            ['codigo' => '040203', 'nombre' => 'Mariano Nicolás Valcárcel',       'prov' => '0402'],
            ['codigo' => '040204', 'nombre' => 'Mariscal Cáceres',                'prov' => '0402'],
            ['codigo' => '040205', 'nombre' => 'Nicolás de Piérola',              'prov' => '0402'],
            ['codigo' => '040206', 'nombre' => 'Ocoña',                           'prov' => '0402'],
            ['codigo' => '040207', 'nombre' => 'Quilca',                          'prov' => '0402'],
            ['codigo' => '040208', 'nombre' => 'Samuel Pastor',                   'prov' => '0402'],
            // Arequipa - Islay
            ['codigo' => '040701', 'nombre' => 'Mollendo',                        'prov' => '0407'],
            ['codigo' => '040702', 'nombre' => 'Cocachacra',                      'prov' => '0407'],
            ['codigo' => '040703', 'nombre' => 'Dean Valdivia',                   'prov' => '0407'],
            ['codigo' => '040704', 'nombre' => 'Islay',                           'prov' => '0407'],
            ['codigo' => '040705', 'nombre' => 'Mejía',                           'prov' => '0407'],
            ['codigo' => '040706', 'nombre' => 'Punta de Bombón',                 'prov' => '0407'],

            // ---- LA LIBERTAD - TRUJILLO ----
            ['codigo' => '130101', 'nombre' => 'Trujillo',                        'prov' => '1301'],
            ['codigo' => '130102', 'nombre' => 'El Porvenir',                     'prov' => '1301'],
            ['codigo' => '130103', 'nombre' => 'Florencia de Mora',               'prov' => '1301'],
            ['codigo' => '130104', 'nombre' => 'Huanchaco',                       'prov' => '1301'],
            ['codigo' => '130105', 'nombre' => 'La Esperanza',                    'prov' => '1301'],
            ['codigo' => '130106', 'nombre' => 'Laredo',                          'prov' => '1301'],
            ['codigo' => '130107', 'nombre' => 'Moche',                           'prov' => '1301'],
            ['codigo' => '130108', 'nombre' => 'Poroto',                          'prov' => '1301'],
            ['codigo' => '130109', 'nombre' => 'Salaverry',                       'prov' => '1301'],
            ['codigo' => '130110', 'nombre' => 'Simbal',                          'prov' => '1301'],
            ['codigo' => '130111', 'nombre' => 'Víctor Larco Herrera',            'prov' => '1301'],
            // La Libertad - Pacasmayo
            ['codigo' => '130701', 'nombre' => 'San Pedro de Lloc',               'prov' => '1307'],
            ['codigo' => '130702', 'nombre' => 'Guadalupe',                       'prov' => '1307'],
            ['codigo' => '130703', 'nombre' => 'Jequetepeque',                    'prov' => '1307'],
            ['codigo' => '130704', 'nombre' => 'Pacasmayo',                       'prov' => '1307'],
            ['codigo' => '130705', 'nombre' => 'San José',                        'prov' => '1307'],

            // ---- LAMBAYEQUE - CHICLAYO ----
            ['codigo' => '140101', 'nombre' => 'Chiclayo',                        'prov' => '1401'],
            ['codigo' => '140102', 'nombre' => 'Chongoyape',                      'prov' => '1401'],
            ['codigo' => '140103', 'nombre' => 'Eten',                            'prov' => '1401'],
            ['codigo' => '140104', 'nombre' => 'Eten Puerto',                     'prov' => '1401'],
            ['codigo' => '140105', 'nombre' => 'José Leonardo Ortiz',             'prov' => '1401'],
            ['codigo' => '140106', 'nombre' => 'La Victoria',                     'prov' => '1401'],
            ['codigo' => '140107', 'nombre' => 'Lagunas',                         'prov' => '1401'],
            ['codigo' => '140108', 'nombre' => 'Monsefú',                         'prov' => '1401'],
            ['codigo' => '140109', 'nombre' => 'Nueva Arica',                     'prov' => '1401'],
            ['codigo' => '140110', 'nombre' => 'Oyotún',                          'prov' => '1401'],
            ['codigo' => '140111', 'nombre' => 'Picsi',                           'prov' => '1401'],
            ['codigo' => '140112', 'nombre' => 'Pimentel',                        'prov' => '1401'],
            ['codigo' => '140113', 'nombre' => 'Reque',                           'prov' => '1401'],
            ['codigo' => '140114', 'nombre' => 'Santa Rosa',                      'prov' => '1401'],
            ['codigo' => '140115', 'nombre' => 'Saña',                            'prov' => '1401'],
            ['codigo' => '140116', 'nombre' => 'Cayaltí',                         'prov' => '1401'],
            ['codigo' => '140117', 'nombre' => 'Pátapo',                          'prov' => '1401'],
            ['codigo' => '140118', 'nombre' => 'Pomalca',                         'prov' => '1401'],
            ['codigo' => '140119', 'nombre' => 'Pucalá',                          'prov' => '1401'],
            ['codigo' => '140120', 'nombre' => 'Tumán',                           'prov' => '1401'],
            // Lambayeque - Lambayeque
            ['codigo' => '140301', 'nombre' => 'Lambayeque',                      'prov' => '1403'],
            ['codigo' => '140302', 'nombre' => 'Chóchope',                        'prov' => '1403'],
            ['codigo' => '140303', 'nombre' => 'Illimo',                          'prov' => '1403'],
            ['codigo' => '140304', 'nombre' => 'Jayanca',                         'prov' => '1403'],
            ['codigo' => '140305', 'nombre' => 'Mochumí',                         'prov' => '1403'],
            ['codigo' => '140306', 'nombre' => 'Mórrope',                         'prov' => '1403'],
            ['codigo' => '140307', 'nombre' => 'Motupe',                          'prov' => '1403'],
            ['codigo' => '140308', 'nombre' => 'Olmos',                           'prov' => '1403'],
            ['codigo' => '140309', 'nombre' => 'Pacora',                          'prov' => '1403'],
            ['codigo' => '140310', 'nombre' => 'Salas',                           'prov' => '1403'],
            ['codigo' => '140311', 'nombre' => 'San José',                        'prov' => '1403'],
            ['codigo' => '140312', 'nombre' => 'Tucume',                          'prov' => '1403'],

            // ---- PIURA ----
            ['codigo' => '200101', 'nombre' => 'Piura',                           'prov' => '2001'],
            ['codigo' => '200102', 'nombre' => 'Castilla',                        'prov' => '2001'],
            ['codigo' => '200103', 'nombre' => 'Catacaos',                        'prov' => '2001'],
            ['codigo' => '200104', 'nombre' => 'Cura Mori',                       'prov' => '2001'],
            ['codigo' => '200105', 'nombre' => 'El Tallán',                       'prov' => '2001'],
            ['codigo' => '200106', 'nombre' => 'La Arena',                        'prov' => '2001'],
            ['codigo' => '200107', 'nombre' => 'La Unión',                        'prov' => '2001'],
            ['codigo' => '200108', 'nombre' => 'Las Lomas',                       'prov' => '2001'],
            ['codigo' => '200109', 'nombre' => 'Tambogrande',                     'prov' => '2001'],
            ['codigo' => '200110', 'nombre' => 'Veintiséis de Octubre',           'prov' => '2001'],
            // Piura - Sullana
            ['codigo' => '200601', 'nombre' => 'Sullana',                         'prov' => '2006'],
            ['codigo' => '200602', 'nombre' => 'Bellavista',                      'prov' => '2006'],
            ['codigo' => '200603', 'nombre' => 'Ignacio Escudero',                'prov' => '2006'],
            ['codigo' => '200604', 'nombre' => 'Lancones',                        'prov' => '2006'],
            ['codigo' => '200605', 'nombre' => 'Marcavelica',                     'prov' => '2006'],
            ['codigo' => '200606', 'nombre' => 'Miguel Checa',                    'prov' => '2006'],
            ['codigo' => '200607', 'nombre' => 'Querecotillo',                    'prov' => '2006'],
            ['codigo' => '200608', 'nombre' => 'Salitral',                        'prov' => '2006'],
            // Piura - Paita
            ['codigo' => '200501', 'nombre' => 'Paita',                           'prov' => '2005'],
            ['codigo' => '200502', 'nombre' => 'Amotape',                         'prov' => '2005'],
            ['codigo' => '200503', 'nombre' => 'Arenal',                          'prov' => '2005'],
            ['codigo' => '200504', 'nombre' => 'Colan',                           'prov' => '2005'],
            ['codigo' => '200505', 'nombre' => 'La Huaca',                        'prov' => '2005'],
            ['codigo' => '200506', 'nombre' => 'Tamarindo',                       'prov' => '2005'],
            ['codigo' => '200507', 'nombre' => 'Vichayal',                        'prov' => '2005'],

            // ---- CUSCO ----
            ['codigo' => '080101', 'nombre' => 'Cusco',                           'prov' => '0801'],
            ['codigo' => '080102', 'nombre' => 'Ccorca',                          'prov' => '0801'],
            ['codigo' => '080103', 'nombre' => 'Poroy',                           'prov' => '0801'],
            ['codigo' => '080104', 'nombre' => 'San Jerónimo',                    'prov' => '0801'],
            ['codigo' => '080105', 'nombre' => 'San Sebastián',                   'prov' => '0801'],
            ['codigo' => '080106', 'nombre' => 'Santiago',                        'prov' => '0801'],
            ['codigo' => '080107', 'nombre' => 'Saylla',                          'prov' => '0801'],
            ['codigo' => '080108', 'nombre' => 'Wanchaq',                         'prov' => '0801'],
            // Cusco - Urubamba
            ['codigo' => '081301', 'nombre' => 'Urubamba',                        'prov' => '0813'],
            ['codigo' => '081302', 'nombre' => 'Chinchero',                       'prov' => '0813'],
            ['codigo' => '081303', 'nombre' => 'Huayllabamba',                    'prov' => '0813'],
            ['codigo' => '081304', 'nombre' => 'Machupicchu',                     'prov' => '0813'],
            ['codigo' => '081305', 'nombre' => 'Maras',                           'prov' => '0813'],
            ['codigo' => '081306', 'nombre' => 'Ollantaytambo',                   'prov' => '0813'],
            ['codigo' => '081307', 'nombre' => 'Yucay',                           'prov' => '0813'],

            // ---- TACNA ----
            ['codigo' => '230101', 'nombre' => 'Tacna',                           'prov' => '2301'],
            ['codigo' => '230102', 'nombre' => 'Alto de la Alianza',              'prov' => '2301'],
            ['codigo' => '230103', 'nombre' => 'Calana',                          'prov' => '2301'],
            ['codigo' => '230104', 'nombre' => 'Ciudad Nueva',                    'prov' => '2301'],
            ['codigo' => '230105', 'nombre' => 'Inclán',                          'prov' => '2301'],
            ['codigo' => '230106', 'nombre' => 'Pachía',                          'prov' => '2301'],
            ['codigo' => '230107', 'nombre' => 'Palca',                           'prov' => '2301'],
            ['codigo' => '230108', 'nombre' => 'Pocollay',                        'prov' => '2301'],
            ['codigo' => '230109', 'nombre' => 'Sama',                            'prov' => '2301'],
            ['codigo' => '230110', 'nombre' => 'Coronel Gregorio Albarracín Lanchipa', 'prov' => '2301'],

            // ---- MOQUEGUA ----
            ['codigo' => '180101', 'nombre' => 'Moquegua',                        'prov' => '1801'],
            ['codigo' => '180102', 'nombre' => 'Carumas',                         'prov' => '1801'],
            ['codigo' => '180103', 'nombre' => 'Cuchumbaya',                      'prov' => '1801'],
            ['codigo' => '180104', 'nombre' => 'Samegua',                         'prov' => '1801'],
            ['codigo' => '180105', 'nombre' => 'San Cristóbal',                   'prov' => '1801'],
            ['codigo' => '180106', 'nombre' => 'Torata',                          'prov' => '1801'],
            // Moquegua - Ilo
            ['codigo' => '180301', 'nombre' => 'Ilo',                             'prov' => '1803'],
            ['codigo' => '180302', 'nombre' => 'El Algarrobal',                   'prov' => '1803'],
            ['codigo' => '180303', 'nombre' => 'Pacocha',                         'prov' => '1803'],

            // ---- TUMBES ----
            ['codigo' => '240101', 'nombre' => 'Tumbes',                          'prov' => '2401'],
            ['codigo' => '240102', 'nombre' => 'Corrales',                        'prov' => '2401'],
            ['codigo' => '240103', 'nombre' => 'La Cruz',                         'prov' => '2401'],
            ['codigo' => '240104', 'nombre' => 'Pampas de Hospital',              'prov' => '2401'],
            ['codigo' => '240105', 'nombre' => 'San Jacinto',                     'prov' => '2401'],
            ['codigo' => '240106', 'nombre' => 'San Juan de la Virgen',           'prov' => '2401'],
            // Tumbes - Zarumilla
            ['codigo' => '240301', 'nombre' => 'Zarumilla',                       'prov' => '2403'],
            ['codigo' => '240302', 'nombre' => 'Aguas Verdes',                    'prov' => '2403'],
            ['codigo' => '240303', 'nombre' => 'Matapalo',                        'prov' => '2403'],
            ['codigo' => '240304', 'nombre' => 'Papayal',                         'prov' => '2403'],

            // ---- JUNÍN - HUANCAYO ----
            ['codigo' => '120101', 'nombre' => 'Huancayo',                        'prov' => '1201'],
            ['codigo' => '120102', 'nombre' => 'Carhuacallanga',                  'prov' => '1201'],
            ['codigo' => '120103', 'nombre' => 'Chacapampa',                      'prov' => '1201'],
            ['codigo' => '120104', 'nombre' => 'Chicche',                         'prov' => '1201'],
            ['codigo' => '120105', 'nombre' => 'Chilca',                          'prov' => '1201'],
            ['codigo' => '120106', 'nombre' => 'Chongos Alto',                    'prov' => '1201'],
            ['codigo' => '120107', 'nombre' => 'Chupuro',                         'prov' => '1201'],
            ['codigo' => '120108', 'nombre' => 'Colca',                           'prov' => '1201'],
            ['codigo' => '120109', 'nombre' => 'Cullhuas',                        'prov' => '1201'],
            ['codigo' => '120110', 'nombre' => 'El Tambo',                        'prov' => '1201'],
            ['codigo' => '120111', 'nombre' => 'Huacrapuquio',                    'prov' => '1201'],
            ['codigo' => '120112', 'nombre' => 'Hualhuas',                        'prov' => '1201'],
            ['codigo' => '120113', 'nombre' => 'Huancan',                         'prov' => '1201'],
            ['codigo' => '120114', 'nombre' => 'Huasicancha',                     'prov' => '1201'],
            ['codigo' => '120115', 'nombre' => 'Huayucachi',                      'prov' => '1201'],
            ['codigo' => '120116', 'nombre' => 'Ingenio',                         'prov' => '1201'],
            ['codigo' => '120117', 'nombre' => 'Pariahuanca',                     'prov' => '1201'],
            ['codigo' => '120118', 'nombre' => 'Pilcomayo',                       'prov' => '1201'],
            ['codigo' => '120119', 'nombre' => 'Pucará',                          'prov' => '1201'],
            ['codigo' => '120120', 'nombre' => 'Quichuay',                        'prov' => '1201'],
            ['codigo' => '120121', 'nombre' => 'Quilcas',                         'prov' => '1201'],
            ['codigo' => '120122', 'nombre' => 'San Agustín',                     'prov' => '1201'],
            ['codigo' => '120123', 'nombre' => 'San Jerónimo de Tunán',           'prov' => '1201'],
            ['codigo' => '120124', 'nombre' => 'Saño',                            'prov' => '1201'],
            ['codigo' => '120125', 'nombre' => 'Sapallanga',                      'prov' => '1201'],
            ['codigo' => '120126', 'nombre' => 'Sicaya',                          'prov' => '1201'],
            ['codigo' => '120127', 'nombre' => 'Santo Domingo de Acobamba',       'prov' => '1201'],
            ['codigo' => '120128', 'nombre' => 'Viques',                          'prov' => '1201'],

            // ---- PUNO - PUNO ----
            ['codigo' => '210101', 'nombre' => 'Puno',                            'prov' => '2101'],
            ['codigo' => '210102', 'nombre' => 'Acora',                           'prov' => '2101'],
            ['codigo' => '210103', 'nombre' => 'Amantaní',                        'prov' => '2101'],
            ['codigo' => '210104', 'nombre' => 'Atuncolla',                       'prov' => '2101'],
            ['codigo' => '210105', 'nombre' => 'Capachica',                       'prov' => '2101'],
            ['codigo' => '210106', 'nombre' => 'Chucuito',                        'prov' => '2101'],
            ['codigo' => '210107', 'nombre' => 'Coata',                           'prov' => '2101'],
            ['codigo' => '210108', 'nombre' => 'Huata',                           'prov' => '2101'],
            ['codigo' => '210109', 'nombre' => 'Mañazo',                          'prov' => '2101'],
            ['codigo' => '210110', 'nombre' => 'Paucarcolla',                     'prov' => '2101'],
            ['codigo' => '210111', 'nombre' => 'Pichacani',                       'prov' => '2101'],
            ['codigo' => '210112', 'nombre' => 'Platería',                        'prov' => '2101'],
            ['codigo' => '210113', 'nombre' => 'San Antonio',                     'prov' => '2101'],
            ['codigo' => '210114', 'nombre' => 'Tiquillaca',                      'prov' => '2101'],
            ['codigo' => '210115', 'nombre' => 'Vilque',                          'prov' => '2101'],

            // ---- CAJAMARCA ----
            ['codigo' => '060101', 'nombre' => 'Cajamarca',                       'prov' => '0601'],
            ['codigo' => '060102', 'nombre' => 'Asunción',                        'prov' => '0601'],
            ['codigo' => '060103', 'nombre' => 'Chetilla',                        'prov' => '0601'],
            ['codigo' => '060104', 'nombre' => 'Cospan',                          'prov' => '0601'],
            ['codigo' => '060105', 'nombre' => 'Encañada',                        'prov' => '0601'],
            ['codigo' => '060106', 'nombre' => 'Jesús',                           'prov' => '0601'],
            ['codigo' => '060107', 'nombre' => 'Llacanora',                       'prov' => '0601'],
            ['codigo' => '060108', 'nombre' => 'Los Baños del Inca',              'prov' => '0601'],
            ['codigo' => '060109', 'nombre' => 'Magdalena',                       'prov' => '0601'],
            ['codigo' => '060110', 'nombre' => 'Matara',                          'prov' => '0601'],
            ['codigo' => '060111', 'nombre' => 'Namora',                          'prov' => '0601'],
            ['codigo' => '060112', 'nombre' => 'San Juan',                        'prov' => '0601'],

            // ---- SAN MARTÍN - MOYOBAMBA ----
            ['codigo' => '220101', 'nombre' => 'Moyobamba',                       'prov' => '2201'],
            ['codigo' => '220102', 'nombre' => 'Calzada',                         'prov' => '2201'],
            ['codigo' => '220103', 'nombre' => 'Habana',                          'prov' => '2201'],
            ['codigo' => '220104', 'nombre' => 'Jepelacio',                       'prov' => '2201'],
            ['codigo' => '220105', 'nombre' => 'Soritor',                         'prov' => '2201'],
            ['codigo' => '220106', 'nombre' => 'Yantalo',                         'prov' => '2201'],
            // San Martín - San Martín
            ['codigo' => '220901', 'nombre' => 'Tarapoto',                        'prov' => '2209'],
            ['codigo' => '220902', 'nombre' => 'Alberto Leveau',                  'prov' => '2209'],
            ['codigo' => '220903', 'nombre' => 'Cacatachi',                       'prov' => '2209'],
            ['codigo' => '220904', 'nombre' => 'Chazuta',                         'prov' => '2209'],
            ['codigo' => '220905', 'nombre' => 'Chipurana',                       'prov' => '2209'],
            ['codigo' => '220906', 'nombre' => 'El Porvenir',                     'prov' => '2209'],
            ['codigo' => '220907', 'nombre' => 'Huimbayoc',                       'prov' => '2209'],
            ['codigo' => '220908', 'nombre' => 'Juan Guerra',                     'prov' => '2209'],
            ['codigo' => '220909', 'nombre' => 'La Banda de Shilcayo',            'prov' => '2209'],
            ['codigo' => '220910', 'nombre' => 'Morales',                         'prov' => '2209'],
            ['codigo' => '220911', 'nombre' => 'Papaplaya',                       'prov' => '2209'],
            ['codigo' => '220912', 'nombre' => 'San Antonio',                     'prov' => '2209'],
            ['codigo' => '220913', 'nombre' => 'Sauce',                           'prov' => '2209'],
            ['codigo' => '220914', 'nombre' => 'Shapaja',                         'prov' => '2209'],

            // ---- LORETO - MAYNAS ----
            ['codigo' => '160101', 'nombre' => 'Iquitos',                         'prov' => '1601'],
            ['codigo' => '160102', 'nombre' => 'Alto Nanay',                      'prov' => '1601'],
            ['codigo' => '160103', 'nombre' => 'Fernando Lores',                  'prov' => '1601'],
            ['codigo' => '160104', 'nombre' => 'Indiana',                         'prov' => '1601'],
            ['codigo' => '160105', 'nombre' => 'Las Amazonas',                    'prov' => '1601'],
            ['codigo' => '160106', 'nombre' => 'Mazan',                           'prov' => '1601'],
            ['codigo' => '160107', 'nombre' => 'Napo',                            'prov' => '1601'],
            ['codigo' => '160108', 'nombre' => 'Punchana',                        'prov' => '1601'],
            ['codigo' => '160109', 'nombre' => 'Torres Causana',                  'prov' => '1601'],
            ['codigo' => '160110', 'nombre' => 'Belén',                           'prov' => '1601'],
            ['codigo' => '160111', 'nombre' => 'San Juan Bautista',               'prov' => '1601'],

            // ---- UCAYALI - CORONEL PORTILLO ----
            ['codigo' => '250101', 'nombre' => 'Callería',                        'prov' => '2501'],
            ['codigo' => '250102', 'nombre' => 'Campoverde',                      'prov' => '2501'],
            ['codigo' => '250103', 'nombre' => 'Iparía',                          'prov' => '2501'],
            ['codigo' => '250104', 'nombre' => 'Masisea',                         'prov' => '2501'],
            ['codigo' => '250105', 'nombre' => 'Yarinacocha',                     'prov' => '2501'],
            ['codigo' => '250106', 'nombre' => 'Nueva Requena',                   'prov' => '2501'],
            ['codigo' => '250107', 'nombre' => 'Manantay',                        'prov' => '2501'],

            // ---- MADRE DE DIOS - TAMBOPATA ----
            ['codigo' => '170101', 'nombre' => 'Tambopata',                       'prov' => '1701'],
            ['codigo' => '170102', 'nombre' => 'Inambari',                        'prov' => '1701'],
            ['codigo' => '170103', 'nombre' => 'Las Piedras',                     'prov' => '1701'],
            ['codigo' => '170104', 'nombre' => 'Laberinto',                       'prov' => '1701'],

            // ---- HUANCAVELICA ----
            ['codigo' => '090101', 'nombre' => 'Huancavelica',                    'prov' => '0901'],
            ['codigo' => '090102', 'nombre' => 'Acobambilla',                     'prov' => '0901'],
            ['codigo' => '090103', 'nombre' => 'Acoria',                          'prov' => '0901'],
            ['codigo' => '090104', 'nombre' => 'Conayca',                         'prov' => '0901'],
            ['codigo' => '090105', 'nombre' => 'Cuenca',                          'prov' => '0901'],
            ['codigo' => '090106', 'nombre' => 'Huachocolpa',                     'prov' => '0901'],
            ['codigo' => '090107', 'nombre' => 'Huayllahuara',                    'prov' => '0901'],
            ['codigo' => '090108', 'nombre' => 'Izcuchaca',                       'prov' => '0901'],
            ['codigo' => '090109', 'nombre' => 'Laria',                           'prov' => '0901'],
            ['codigo' => '090110', 'nombre' => 'Manta',                           'prov' => '0901'],
            ['codigo' => '090111', 'nombre' => 'Mariscal Cáceres',                'prov' => '0901'],
            ['codigo' => '090112', 'nombre' => 'Moya',                            'prov' => '0901'],
            ['codigo' => '090113', 'nombre' => 'Nuevo Occoro',                    'prov' => '0901'],
            ['codigo' => '090114', 'nombre' => 'Palca',                           'prov' => '0901'],
            ['codigo' => '090115', 'nombre' => 'Pilchaca',                        'prov' => '0901'],
            ['codigo' => '090116', 'nombre' => 'Vilca',                           'prov' => '0901'],
            ['codigo' => '090117', 'nombre' => 'Yauli',                           'prov' => '0901'],
            ['codigo' => '090118', 'nombre' => 'Ascensión',                       'prov' => '0901'],
            ['codigo' => '090119', 'nombre' => 'Huando',                          'prov' => '0901'],

            // ---- AYACUCHO - HUAMANGA ----
            ['codigo' => '050101', 'nombre' => 'Ayacucho',                        'prov' => '0501'],
            ['codigo' => '050102', 'nombre' => 'Acocro',                          'prov' => '0501'],
            ['codigo' => '050103', 'nombre' => 'Acos Vinchos',                    'prov' => '0501'],
            ['codigo' => '050104', 'nombre' => 'Carmen Alto',                     'prov' => '0501'],
            ['codigo' => '050105', 'nombre' => 'Chiara',                          'prov' => '0501'],
            ['codigo' => '050106', 'nombre' => 'Ocros',                           'prov' => '0501'],
            ['codigo' => '050107', 'nombre' => 'Pacaycasa',                       'prov' => '0501'],
            ['codigo' => '050108', 'nombre' => 'Quinua',                          'prov' => '0501'],
            ['codigo' => '050109', 'nombre' => 'San José de Ticllas',             'prov' => '0501'],
            ['codigo' => '050110', 'nombre' => 'San Juan Bautista',               'prov' => '0501'],
            ['codigo' => '050111', 'nombre' => 'Santiago de Pischa',              'prov' => '0501'],
            ['codigo' => '050112', 'nombre' => 'Socos',                           'prov' => '0501'],
            ['codigo' => '050113', 'nombre' => 'Tambillo',                        'prov' => '0501'],
            ['codigo' => '050114', 'nombre' => 'Vinchos',                         'prov' => '0501'],
            ['codigo' => '050115', 'nombre' => 'Jesús Nazareno',                  'prov' => '0501'],

            // ---- HUÁNUCO ----
            ['codigo' => '100101', 'nombre' => 'Huánuco',                         'prov' => '1001'],
            ['codigo' => '100102', 'nombre' => 'Amarilis',                        'prov' => '1001'],
            ['codigo' => '100103', 'nombre' => 'Chinchao',                        'prov' => '1001'],
            ['codigo' => '100104', 'nombre' => 'Churubamba',                      'prov' => '1001'],
            ['codigo' => '100105', 'nombre' => 'Margos',                          'prov' => '1001'],
            ['codigo' => '100106', 'nombre' => 'Quisqui (Kichki)',                'prov' => '1001'],
            ['codigo' => '100107', 'nombre' => 'San Francisco de Cayran',         'prov' => '1001'],
            ['codigo' => '100108', 'nombre' => 'San Pedro de Chaulan',            'prov' => '1001'],
            ['codigo' => '100109', 'nombre' => 'Santa María del Valle',           'prov' => '1001'],
            ['codigo' => '100110', 'nombre' => 'Yarumayo',                        'prov' => '1001'],
            ['codigo' => '100111', 'nombre' => 'Pillco Marca',                    'prov' => '1001'],
        ];

        foreach ($distritos as $dist) {
            $prov = DB::table('provincias')->where('codigo', $dist['prov'])->first();
            if (!$prov) continue;

            DB::table('distritos')->insert([
                'codigo'          => $dist['codigo'],
                'nombre'          => $dist['nombre'],
                'slug'            => Str::slug($dist['nombre'] . '-' . $dist['codigo']),
                'provincia_id'    => $prov->id,
                'departamento_id' => $prov->departamento_id,
                'activo'          => true,
                'created_at'      => now(),
                'updated_at'      => now(),
            ]);
        }
    }
}
